// Saudi Arabia — all 13 administrative regions and their major cities/towns.
// Hardcoded (no API). Used by components/SaudiCityPicker.tsx.

export interface SaudiCity {
  ar: string;
  en: string;
}

export interface SaudiRegion {
  id: string;
  nameAr: string;
  nameEn: string;
  cities: SaudiCity[];
}

export const SAUDI_REGIONS: SaudiRegion[] = [
  {
    id: 'riyadh',
    nameAr: 'منطقة الرياض',
    nameEn: 'Riyadh Region',
    cities: [
      { ar: 'الرياض', en: 'Riyadh' },
      { ar: 'الخرج', en: 'Al Kharj' },
      { ar: 'الدوادمي', en: 'Ad Dawadimi' },
      { ar: 'المجمعة', en: 'Al Majmaah' },
      { ar: 'القويعية', en: 'Al Quwaiyah' },
      { ar: 'وادي الدواسر', en: 'Wadi ad-Dawasir' },
      { ar: 'الأفلاج', en: 'Al Aflaj' },
      { ar: 'الزلفي', en: 'Az Zulfi' },
      { ar: 'شقراء', en: 'Shaqra' },
      { ar: 'حوطة بني تميم', en: 'Hotat Bani Tamim' },
      { ar: 'عفيف', en: 'Afif' },
      { ar: 'الدرعية', en: 'Diriyah' },
      { ar: 'الدلم', en: 'Ad Dilam' },
      { ar: 'ثادق', en: 'Thadiq' },
      { ar: 'حريملاء', en: 'Huraymila' },
      { ar: 'المزاحمية', en: 'Al Muzahimiyah' },
      { ar: 'رماح', en: 'Rumah' },
      { ar: 'الغاط', en: 'Al Ghat' },
      { ar: 'مرات', en: 'Marat' },
    ],
  },
  {
    id: 'makkah',
    nameAr: 'منطقة مكة المكرمة',
    nameEn: 'Makkah Region',
    cities: [
      { ar: 'مكة المكرمة', en: 'Makkah' },
      { ar: 'جدة', en: 'Jeddah' },
      { ar: 'الطائف', en: 'Taif' },
      { ar: 'رابغ', en: 'Rabigh' },
      { ar: 'القنفذة', en: 'Al Qunfudhah' },
      { ar: 'الليث', en: 'Al Lith' },
      { ar: 'خليص', en: 'Khulais' },
      { ar: 'الجموم', en: 'Al Jumum' },
      { ar: 'تربة', en: 'Turbah' },
      { ar: 'رنية', en: 'Ranyah' },
      { ar: 'أضم', en: 'Adham' },
      { ar: 'الكامل', en: 'Al Kamil' },
      { ar: 'بحرة', en: 'Bahrah' },
      { ar: 'المويه', en: 'Al Muwayh' },
    ],
  },
  {
    id: 'madinah',
    nameAr: 'منطقة المدينة المنورة',
    nameEn: 'Madinah Region',
    cities: [
      { ar: 'المدينة المنورة', en: 'Madinah' },
      { ar: 'ينبع', en: 'Yanbu' },
      { ar: 'العلا', en: 'Al Ula' },
      { ar: 'بدر', en: 'Badr' },
      { ar: 'خيبر', en: 'Khaybar' },
      { ar: 'الحناكية', en: 'Al Hinakiyah' },
      { ar: 'مهد الذهب', en: 'Mahd adh Dhahab' },
      { ar: 'العيص', en: 'Al Ais' },
    ],
  },
  {
    id: 'eastern',
    nameAr: 'المنطقة الشرقية',
    nameEn: 'Eastern Province',
    cities: [
      { ar: 'الدمام', en: 'Dammam' },
      { ar: 'الخبر', en: 'Al Khobar' },
      { ar: 'الظهران', en: 'Dhahran' },
      { ar: 'الأحساء', en: 'Al Ahsa' },
      { ar: 'الهفوف', en: 'Hofuf' },
      { ar: 'المبرز', en: 'Al Mubarraz' },
      { ar: 'القطيف', en: 'Qatif' },
      { ar: 'الجبيل', en: 'Jubail' },
      { ar: 'حفر الباطن', en: 'Hafar Al Batin' },
      { ar: 'سيهات', en: 'Saihat' },
      { ar: 'صفوى', en: 'Safwa' },
      { ar: 'تاروت', en: 'Tarout' },
      { ar: 'رأس تنورة', en: 'Ras Tanura' },
      { ar: 'بقيق', en: 'Abqaiq' },
      { ar: 'الخفجي', en: 'Khafji' },
      { ar: 'النعيرية', en: 'Nairyah' },
      { ar: 'قرية العليا', en: 'Qaryat Al Ulya' },
      { ar: 'العيون', en: 'Al Uyun' },
    ],
  },
  {
    id: 'asir',
    nameAr: 'منطقة عسير',
    nameEn: 'Asir Region',
    cities: [
      { ar: 'أبها', en: 'Abha' },
      { ar: 'خميس مشيط', en: 'Khamis Mushait' },
      { ar: 'بيشة', en: 'Bisha' },
      { ar: 'النماص', en: 'An Namas' },
      { ar: 'محايل عسير', en: 'Mahayil' },
      { ar: 'سراة عبيدة', en: 'Sarat Abidah' },
      { ar: 'تثليث', en: 'Tathlith' },
      { ar: 'رجال ألمع', en: 'Rijal Almaa' },
      { ar: 'ظهران الجنوب', en: 'Dhahran Al Janub' },
      { ar: 'بلقرن', en: 'Balqarn' },
      { ar: 'أحد رفيدة', en: 'Ahad Rufaidah' },
      { ar: 'تنومة', en: 'Tanomah' },
    ],
  },
  {
    id: 'tabuk',
    nameAr: 'منطقة تبوك',
    nameEn: 'Tabuk Region',
    cities: [
      { ar: 'تبوك', en: 'Tabuk' },
      { ar: 'ضباء', en: 'Duba' },
      { ar: 'أملج', en: 'Umluj' },
      { ar: 'حقل', en: 'Haql' },
      { ar: 'الوجه', en: 'Al Wajh' },
      { ar: 'تيماء', en: 'Tayma' },
    ],
  },
  {
    id: 'qassim',
    nameAr: 'منطقة القصيم',
    nameEn: 'Qassim Region',
    cities: [
      { ar: 'بريدة', en: 'Buraydah' },
      { ar: 'عنيزة', en: 'Unaizah' },
      { ar: 'الرس', en: 'Ar Rass' },
      { ar: 'البكيرية', en: 'Al Bukayriyah' },
      { ar: 'المذنب', en: 'Al Mithnab' },
      { ar: 'البدائع', en: 'Al Badai' },
      { ar: 'رياض الخبراء', en: 'Riyadh Al Khabra' },
      { ar: 'عيون الجواء', en: 'Uyun Al Jiwa' },
      { ar: 'النبهانية', en: 'An Nabhaniyah' },
      { ar: 'الشماسية', en: 'Ash Shimasiyah' },
    ],
  },
  {
    id: 'hail',
    nameAr: 'منطقة حائل',
    nameEn: 'Hail Region',
    cities: [
      { ar: 'حائل', en: 'Hail' },
      { ar: 'بقعاء', en: 'Baqaa' },
      { ar: 'الغزالة', en: 'Al Ghazalah' },
      { ar: 'الشنان', en: 'Ash Shinan' },
      { ar: 'الشملي', en: 'Ash Shamli' },
      { ar: 'موقق', en: 'Mawqaq' },
      { ar: 'السليمي', en: 'As Sulaymi' },
    ],
  },
  {
    id: 'northern',
    nameAr: 'منطقة الحدود الشمالية',
    nameEn: 'Northern Borders Region',
    cities: [
      { ar: 'عرعر', en: 'Arar' },
      { ar: 'رفحاء', en: 'Rafha' },
      { ar: 'طريف', en: 'Turaif' },
      { ar: 'العويقيلة', en: 'Al Uwayqilah' },
    ],
  },
  {
    id: 'jazan',
    nameAr: 'منطقة جازان',
    nameEn: 'Jazan Region',
    cities: [
      { ar: 'جازان', en: 'Jazan' },
      { ar: 'صبيا', en: 'Sabya' },
      { ar: 'أبو عريش', en: 'Abu Arish' },
      { ar: 'صامطة', en: 'Samtah' },
      { ar: 'أحد المسارحة', en: 'Ahad Al Masarihah' },
      { ar: 'فرسان', en: 'Farasan' },
      { ar: 'بيش', en: 'Baish' },
      { ar: 'الدرب', en: 'Ad Darb' },
      { ar: 'العارضة', en: 'Al Aridah' },
      { ar: 'ضمد', en: 'Damad' },
    ],
  },
  {
    id: 'najran',
    nameAr: 'منطقة نجران',
    nameEn: 'Najran Region',
    cities: [
      { ar: 'نجران', en: 'Najran' },
      { ar: 'شرورة', en: 'Sharurah' },
      { ar: 'حبونا', en: 'Hubuna' },
      { ar: 'بدر الجنوب', en: 'Badr Al Janub' },
      { ar: 'يدمة', en: 'Yadamah' },
      { ar: 'خباش', en: 'Khubash' },
      { ar: 'ثار', en: 'Thar' },
    ],
  },
  {
    id: 'bahah',
    nameAr: 'منطقة الباحة',
    nameEn: 'Al Bahah Region',
    cities: [
      { ar: 'الباحة', en: 'Al Bahah' },
      { ar: 'بلجرشي', en: 'Baljurashi' },
      { ar: 'المندق', en: 'Al Mandaq' },
      { ar: 'المخواة', en: 'Al Mikhwah' },
      { ar: 'قلوة', en: 'Qilwah' },
      { ar: 'العقيق', en: 'Al Aqiq' },
      { ar: 'القرى', en: 'Al Qura' },
    ],
  },
  {
    id: 'jawf',
    nameAr: 'منطقة الجوف',
    nameEn: 'Al Jawf Region',
    cities: [
      { ar: 'سكاكا', en: 'Sakaka' },
      { ar: 'القريات', en: 'Al Qurayyat' },
      { ar: 'دومة الجندل', en: 'Dumat Al Jandal' },
      { ar: 'طبرجل', en: 'Tabarjal' },
    ],
  },
];
