-- §3/§4 — seed a strong initial catalog so the admin pricing screens are
-- populated out of the box (not empty shells). Guarded: only seeds when a table
-- is empty, so admin edits and re-runs are never clobbered. Repair rules key on
-- repair_type = the issue-catalog id at its baseline estimatedPrice, so
-- estimates are identical to before while the catalog is fully editable.

insert into public.pricing_addons (kind, device_type, item_key, name_ar, name_en, price, sort)
select * from (values
  ('accessory','phone','charger','شاحن','Charger',60,1),
  ('accessory','phone','cable','كيبل شحن','Charging cable',25,2),
  ('accessory','phone','adapter','محول','Adapter',40,3),
  ('accessory','phone','case','جراب حماية','Protective case',35,4),
  ('accessory','phone','screen_protector','واقي شاشة','Screen protector',30,5),
  ('accessory','phone','power_bank','باور بانك','Power bank',90,6),
  ('accessory','phone','earphones','سماعات','Earphones',70,7),
  ('accessory','tablet','charger','شاحن','Charger',70,1),
  ('accessory','tablet','cable','كيبل شحن','Charging cable',30,2),
  ('accessory','tablet','case','جراب حماية','Protective case',55,3),
  ('accessory','tablet','screen_protector','واقي شاشة','Screen protector',45,4),
  ('accessory','tablet','stylus','قلم','Stylus pen',90,5),
  ('accessory','laptop','charger','شاحن/محول','Charger / adapter',130,1),
  ('accessory','laptop','case','حقيبة','Laptop sleeve',70,2),
  ('accessory','laptop','mouse','ماوس','Mouse',50,3),
  ('accessory','laptop','keyboard','لوحة مفاتيح','Keyboard accessory',80,4),
  ('accessory','laptop','cooling_pad','قاعدة تبريد','Cooling pad',75,5),
  ('accessory','watch','charger','شاحن','Charger',45,1),
  ('accessory','watch','strap','سوار','Watch strap',40,2),
  ('accessory','watch','screen_protector','واقي شاشة','Screen protector',25,3),
  ('accessory','gaming','controller','يد تحكم','Controller',180,1),
  ('accessory','gaming','cable','كيبل','Cable',30,2),
  ('accessory','gaming','charging_dock','قاعدة شحن','Charging dock',90,3),
  ('accessory','gaming','headset','سماعة','Gaming headset',150,4),
  ('accessory','tv','remote','ريموت تحكم','Remote control',60,1),
  ('accessory','tv','wall_mount','حامل جداري','Wall mount',90,2),
  ('accessory','tv','hdmi','كيبل HDMI','HDMI cable',35,3),
  ('accessory','tv','cleaning_kit','طقم تنظيف الشاشة','Screen cleaning kit',30,4),
  ('accessory','headphones','ear_tips','سدادات أذن','Ear tips',25,1),
  ('accessory','headphones','case','علبة حماية','Protective case',35,2),
  ('accessory','headphones','cable','كيبل شحن','Charging cable',25,3),
  ('accessory',null,'charger','شاحن','Charger',50,1),
  ('accessory',null,'cable','كيبل','Cable',25,2),
  ('accessory',null,'case','حافظة','Case',35,3),
  ('protection',null,'screen_protector','واقي شاشة مركّب','Installed screen protector',40,1),
  ('protection',null,'protective_case','كفر حماية','Protective case',50,2),
  ('protection',null,'full_protection','باقة الحماية الشاملة','Full protection package',120,3)
) as v(kind, device_type, item_key, name_ar, name_en, price, sort)
where not exists (select 1 from public.pricing_addons);

insert into public.pricing_rules (device_type, repair_type, price, source)
select v.device_type, v.repair_type, v.price, 'manual'
from (values
  ('phone','screen',280),
  ('phone','battery',160),
  ('phone','charging',130),
  ('phone','camera',220),
  ('phone','speaker',130),
  ('phone','back-glass',200),
  ('phone','water-damage',350),
  ('phone','software',120),
  ('phone','phone-mic',140),
  ('phone','phone-earpiece',140),
  ('phone','phone-biometrics',250),
  ('phone','phone-buttons',120),
  ('phone','phone-network',160),
  ('phone','phone-no-power',200),
  ('phone','phone-data-recovery',250),
  ('laptop','laptop-screen',550),
  ('laptop','keyboard',250),
  ('laptop','laptop-battery',320),
  ('laptop','laptop-upgrade',350),
  ('laptop','laptop-os',150),
  ('laptop','laptop-hinge',250),
  ('laptop','laptop-liquid',500),
  ('laptop','laptop-overheat',150),
  ('laptop','laptop-charging',180),
  ('laptop','laptop-motherboard',450),
  ('laptop','laptop-data-recovery',300),
  ('laptop','laptop-wifi',130),
  ('laptop','laptop-speaker',160),
  ('tablet','tablet-screen',500),
  ('tablet','tablet-battery',320),
  ('tablet','tablet-charging',200),
  ('tablet','tablet-software',150),
  ('tablet','tablet-camera',180),
  ('tablet','tablet-speaker',150),
  ('tablet','tablet-buttons',130),
  ('tablet','tablet-liquid',300),
  ('watch','watch-screen',380),
  ('watch','watch-battery',200),
  ('watch','watch-crown',200),
  ('watch','watch-charging',140),
  ('watch','watch-strap',80),
  ('watch','watch-sensor',180),
  ('watch','watch-software',100),
  ('printer','printer-paper',100),
  ('printer','printer-ink',150),
  ('headphones','audio-one-side',120),
  ('tv','tv-screen',800),
  ('appliance','appliance-power',200),
  ('gaming','gaming-no-power',250),
  ('gaming','gaming-hdmi',300),
  ('gaming','gaming-overheat',200),
  ('gaming','gaming-disc',280),
  ('gaming','gaming-controller',120),
  ('gaming','gaming-storage',200),
  ('gaming','gaming-port',160),
  ('gaming','gaming-software',130)
) as v(device_type, repair_type, price)
where not exists (select 1 from public.pricing_rules);
